// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kudoyccddmdilphlwann.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1ZG95Y2NkZG1kaWxwaGx3YW5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyODE0OTQsImV4cCI6MjA2MTg1NzQ5NH0.i71chvgQYNN3iM1xYFatt3ff1p-sR0Wiz15V5K5rZaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);